version: '3.9'
services:
  spark-master:
    image: apache/spark:latest
    container_name: spark-master
    user: root
    command: |
      apt-get update &&
      apt-get install --no-install-recommends -y python3 &&
      pip install --upgrade pip &&
      python3 -m venv venv &&
      cd /home/eegspark &&
      pip install -r requirements.txt &&
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
    volumes:
      - D:\file\matprocess\eegspark-docker:/home

  spark-worker:
    image: apache/spark:latest
    container_name: spark-worker
    user: root
    command: |
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=1g
      - SPARK_WORKER_PORT=8881
      - SPARK_WORKER_WEBUI_PORT=8081
networks:
  spark-net:
    driver: bridge
